server:
  port: 8093

spring:
  output:
    ansi:
      enabled: always
  datasource:
    initialization-mode: always # 使用脚本进行初始化
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/springbucks?useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: springbucks
    password: springbucks
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: spring
    password: spring
  cloud:
    stream:
      bindings:
        newOrders:
          group: barista-service


order:
  barista-prefix: frog-barista-


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always