server:
  port: 8090 # 0的话, 指示随机使用一个端口
  error:
    include-exception: false # 开发环境开启, 用于前台输出错误日志
    include-stacktrace: never # 开发环境开启, 用于前台输出错误日志
feign:
  client:
    config:
      default:
        connection-timeout: 500
        read-timeout: 500
  hystrix:
    enabled: true  # 指示是否启用hystrix熔断

logging:
  level:
    sch.frog.learn.spring.client.integration.CoffeeService : debug
spring:
  cloud:
    zookeeper:  # zookeeper注册中心
      connect-string: 127.0.0.1:2181
    consul: # consul注册中心
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
    nacos: # nacos注册中心
      discovery:
        server-addr: 127.0.0.1:8848

frog:
  discovery:
    enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"