server:
  port: 0 # 指示随机使用一个端口
feign:
  client:
    config:
      default:
        connection-timeout: 500
        read-timeout: 500

logging:
  level:
    sch.frog.learn.spring.client.integration.CoffeeService : debug
spring:
  cloud:
    zookeeper:  # zookeeper作为注册中心
      connect-string: 192.168.99.100:2181
    consul: # consul作为注册中心
      host: 192.168.99.100
      port: 8500
      discovery:
        prefer-ip-address: true