server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      discovery:
        prefer-ip-address: true
    config:
      server:
        git:
          uri: file://D:/Java/SpringDemo/config
