server:
  port: 8091 # 0的话, 指示随机使用一个端口
  error:
    include-exception: false # 开发环境开启, 用于前台输出错误日志
    include-stacktrace: never # 开发环境开启, 用于前台输出错误日志
feign:
  client:
    config:
      default:
        connection-timeout: 500
        read-timeout: 500

logging:
  level:
    sch.frog.learn.spring.client.integration.CoffeeService : debug
spring:
  cloud:
    consul: # consul注册中心
      host: 192.168.99.100
      port: 8500
      discovery:
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
resilience4j:
  circuitbreaker:
    backends:
      order:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        ring-buffer-size-in-close-state: 5
        ring-buffer-size-in-half-open-state: 3
        event-consumer-buffer-size: 10
      menu:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        ring-buffer-size-in-close-state: 5
        ring-buffer-size-in-half-open-state: 3
        event-consumer-buffer-size: 10
  bulkhead:
    backends:
      order:
        max-concurrent-call: 1
        max-wait-time: 5
      menu:
        max-concurrent-call: 5
        max-wait-time: 5