# 不做端口配置时, 默认使用8080端口
spring:
  datasource:
    initialization-mode: always # 使用脚本进行初始化
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.99.100/springbucks?useSSL=false&allowPublicKeyRetrieval=true
#    username: springbucks
#    password: springbucks
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
#    password: n/z7PyA5cvcXvs8px8FVmBVpaRyNsvJb3X7YfS38DJrIg25EbZaZGvH4aHcnc97Om0islpCAPc3MqsGvsrxVJw==
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5
      filters: conn, config, stat, slf4j
#      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}  # druid密码加密
      filter:
        config:
          enabled: true
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: SELECT 1
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 5
#      idle-timeout: 600000
#      connection-timeout: 30000
#      max-lifetime: 1800000
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    mongodb:
      uri: mongodb://springbucks:springbucks@192.168.99.100:27017/springbucks
  cache:
    type: redis
    cache-names: coffee
    redis:
      time-to-live: 5000
      cache-null-values: false
  redis:
    host: 192.168.99.100
    port: 6379
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
  thymeleaf:
    cache: false  # 开发环境, 不使用thymeleaf缓存
  mvc:
    static-path-pattern: /static/**
  resources:
    cache:
      cachecontrol:
        max-age: 20s
        # no-cache: true
  session:
    store-type: redis

# Spring boot actuator端点启用和暴露
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 数据库加密秘钥
# public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALS8ng1XvgHrdOgm4pxrnUdt3sXtu/E8My9KzX8sXlz+mXRZQCop7NVQLne25pXHtZoDYuMh3bzoGj6v5HvvAQ8CAwEAAQ==


# mybatis
mybatis:
  type-handlers-package: frog.learn.spring.mybatis.common.typehandler
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: frog.learn.spring.**.model
  mapper-locations: classpath*:/mapper/**/*.xml
pagehelper:
  page-size-zero: true  #如果pageSize传入的是0, 则查询全部
  offset-as-page-num: true # 指示pageNum参数表示的页码, 而不是记录的offset
  reasonable: true  # 如果pageNum小于0时自动处理
  support-methods-arguments: true # 方法参数支持


redis:
  host: 192.168.99.100
  maxTotal: 5
  maxIdle: 5
  testOnBorrow : true

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

